---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    REDSHIFT_DB_NAME: dev
    REDSHIFT_TABLE: patron_info_dev
    GEOCODER_API_BASE_URL: https://geocoding.geo.census.gov/geocoder/geographies/addressbatch
    GEOCODER_API_BENCHMARK: Public_AR_Current
    GEOCODER_API_VINTAGE: Current_Current
    PATRON_INFO_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/PatronInfo
    KINESIS_BATCH_SIZE: 20
    S3_BUCKET: bic-poller-states-qa
    S3_RESOURCE: patron_info_poller_state.json
    SIERRA_BATCH_SIZE: 20
    LOG_LEVEL: info
    MAX_BATCHES: 3
    IGNORE_CACHE: True
    BACKFILL: False
    STARTING_CREATION_DT: 2022-01-01 00:00:00-05
    STARTING_UPDATE_DT: 2022-01-01 00:00:00-05
    STARTING_DELETION_DATE: 2022-01-01
ENCRYPTED_VARIABLES:
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCu20jxZpTC9cf9V8QIBEIAmt4TZJ7JuFQ1C845HxG8wAXzC7SFHkMNe4U6rKlD1twveXygfiQc=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGcwZQYJKoZIhvcNAQcGoFgwVgIBADBRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCV82BNYC3MGUFAVfwIBEIAkpG132958p9Tz//Np8BENFyL5bk+NRkJXR+T+Z0/MKFxKTX4n
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNOcPC3X2RjvquQnGgIBEIAm5iOucK+WlUlaV48b+F+85N3H30+HQPihI79g48aOpwHhI6YLjVY=
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKVt6J4k13w+FSM2iQIBEIAm7jxrRsDCNS4hQfPR07XhsvTE9NnM7OldE6IeVvyQKvGTtGhaUPk=
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDE+Cpoz/xSJfghw9HgIBEIAvX/fJGbtNzn1fPVMvLyp3+UmUZG4Xymf+VE+UyGdW22EPmNsmYZFKNLLV0i8OsFk=
    GEOCODER_API_KEY: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAz3qMg7YHTJLH8q8P8CARCAQy9eRApQmcT9vpsPBDT+Shh3YFxHA9fT8O1KWeg8v0gzzAy2Hn9GrQSVVFfGoFuBwiEL+/t/TFl5W/HKuKYiB//YYho=
    KINESIS_STREAM_ARN: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJ0wgZoGCSqGSIb3DQEHBqCBjDCBiQIBADCBgwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAx+1zfSw83hVndfrCQCARCAVizfs/c9ETEczKdO+BUk2unL4+ACx9nLiFjbCMxwCV+eK6NrC3a5QO+BHs0SXn5GimF086lo6m0Nu/H/WhJloLYEdaZSuStD4/uNTE3eU4ZUtWU/V0ah
    BCRYPT_SALT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHsweQYJKoZIhvcNAQcGoGwwagIBADBlBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFqhoI9xSv6texISOgIBEIA4dj5hPgp5DZ4sg0MmWdjZ0oh5X3+4dEMijJxgaeE7S5xOfNHRXU92wHHPbOlwtc0ytRiOuONNZLo=
...