---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    REDSHIFT_CLUSTER: nypl-dw-production
    REDSHIFT_DB_NAME: dev
    GEOCODER_API_BASE_URL: https://geocoding.geo.census.gov/geocoder/geographies/addressbatch
    GEOCODER_API_BENCHMARK: Public_AR_Current
    GEOCODER_API_VINTAGE: Current_Current
    SIERRA_BATCH_SIZE: 20
    LOG_LEVEL: debug
ENCRYPTED_VARIABLES:
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCu20jxZpTC9cf9V8QIBEIAmt4TZJ7JuFQ1C845HxG8wAXzC7SFHkMNe4U6rKlD1twveXygfiQc=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGcwZQYJKoZIhvcNAQcGoFgwVgIBADBRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDwzqnB5BPW+xaeIfwIBEIAkY2VpNvtIe6ABU4z5K9NKgyWrF/vmcKoYWzEInaolcl88Bzyh
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGgwZgYJKoZIhvcNAQcGoFkwVwIBADBSBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJ4TkGy105+hINMtQwIBEIAlXJwR4gyTbFr1DwHoRQRTmzEDF3dsrsBl4o2HMYGoXA5xLT4eIg==
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGXDu9J2GaJgBookEQIBEIAoymWeOZ2JdGYg/NzmK6jWkPLcHTGAGYUnRp2B829fcAlqjrLGFpCdww==
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGYwZAYJKoZIhvcNAQcGoFcwVQIBADBQBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDD/2nYQFfbxFVCnnoQIBEIAjsmUKufk4vfchYxyeKjpFpzzUeb9HgxTN/NWTUFnUVh5WsbM=
    BCRYPT_SALT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHsweQYJKoZIhvcNAQcGoGwwagIBADBlBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFqhoI9xSv6texISOgIBEIA4dj5hPgp5DZ4sg0MmWdjZ0oh5X3+4dEMijJxgaeE7S5xOfNHRXU92wHHPbOlwtc0ytRiOuONNZLo=
...