---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    REDSHIFT_DB_NAME: qa
    REDSHIFT_TABLE: patron_info_qa
    GEOCODER_API_BASE_URL: https://geocoding.geo.census.gov/geocoder/geographies/addressbatch
    GEOCODER_API_BENCHMARK: Public_AR_Current
    GEOCODER_API_VINTAGE: Current_Current
    PATRON_INFO_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/PatronInfo
    KINESIS_STREAM_NAME: PatronInfo-qa
    KINESIS_BATCH_SIZE: 500
    S3_BUCKET: bic-poller-states-qa
    S3_RESOURCE: patron_info_poller_state.json
    SIERRA_BATCH_SIZE: 100
    LOG_LEVEL: info
ENCRYPTED_VARIABLES:
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDL6zq0QQYBhdW4rz8gIBEIApxucxIVAb1Ec4uHUAwxRZcvC8OAZxuj/oJAkhCPh8sPJJ08w3ECoXoKk=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGcwZQYJKoZIhvcNAQcGoFgwVgIBADBRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCV82BNYC3MGUFAVfwIBEIAkpG132958p9Tz//Np8BENFyL5bk+NRkJXR+T+Z0/MKFxKTX4n
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNOcPC3X2RjvquQnGgIBEIAm5iOucK+WlUlaV48b+F+85N3H30+HQPihI79g48aOpwHhI6YLjVY=
    REDSHIFT_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKIwgZ8GCSqGSIb3DQEHBqCBkTCBjgIBADCBiAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzfC7it2NYa1YnFy+4CARCAW1NrqGfSfPptEF4epEXl8Hr6ntrJcZ0DE1GeGt2c2mMnMt7hcim39NTgxHvi5DIldF4J2UJzgG0KBs5UGRU9dyjrQu5zLfdB8Kv50d1lHfvqM2aDQAK0SQ188BY=
    REDSHIFT_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDKVt6J4k13w+FSM2iQIBEIAm7jxrRsDCNS4hQfPR07XhsvTE9NnM7OldE6IeVvyQKvGTtGhaUPk=
    REDSHIFT_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDE+Cpoz/xSJfghw9HgIBEIAvX/fJGbtNzn1fPVMvLyp3+UmUZG4Xymf+VE+UyGdW22EPmNsmYZFKNLLV0i8OsFk=
    BCRYPT_SALT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAHsweQYJKoZIhvcNAQcGoGwwagIBADBlBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFqhoI9xSv6texISOgIBEIA4dj5hPgp5DZ4sg0MmWdjZ0oh5X3+4dEMijJxgaeE7S5xOfNHRXU92wHHPbOlwtc0ytRiOuONNZLo=
...